make:
	g++ main.cpp -o SHOGUN-DUEL -Wall -Wconversion -Weffc++ -pedantic-errors -lsfml-graphics -lsfml-window -lsfml-system -std=c++20 -g 

# -o0 is an no-optimization flag for easier debugging
# -pedantic-errors is a no-compiler-extension flag for generating a standard behavior
# -lsfml-graphics -lsfml-window -lsfml-system is a SFML specifier flag
# -Wall -Wconversion -Weffc++ are for warning checking 